# -*- coding: utf-8 -*-
"""投稿用v14 フォルダを v13 の図表・表・補遺から組み立てる。

v14 は数値の再計算を伴わない。処理は3つ。

1. **Suppl Fig S1 を落として S2〜S5 を S1〜S4 に繰り上げる**（付記16-1）。
   ファイル名・CSVの説明行・まとめ xlsx のシート名とグラフタイトル・
   まとめ pptx のスライドタイトル・Figure2/Figure6 の note を書き換える。
   xlsx のシート名はグラフの参照式（`'S2A'!$B$2:$B$12`）にも現れるため、
   openpyxl で開かず zip の XML を直接書き換える（ネイティブグラフを壊さない）。
2. **Figure2・Figure4・Figure6 の PNG を pptx から書き出し直す**（付記16-4）。
   Figure4 は v13 で pptx のキャプションだけ訂正され PNG が古いままだった。
   Figure2・Figure6 は 1. で note の Suppl Fig 番号が変わる。
3. README を v14 に書き換える。

原稿（docx・md）は apply_docx_v14.py / apply_md_v14.py が生成する。

実行: python build_v14_folder.py
Windows + PowerPoint が必要（PNG 書き出しに PowerPoint COM を使う）。
"""
import io
import os
import re
import shutil
import sys
import zipfile

BASE = os.path.dirname(os.path.abspath(__file__))
NEW = os.path.join(BASE, "05_論文成果物", "公費含めない_new")
KAITEI = os.path.join(NEW, "投稿改定ver")
V13 = os.path.join(KAITEI, "投稿用v13")
V14 = os.path.join(KAITEI, "投稿用v14")

sys.path.insert(0, KAITEI)
from build_submission_v10 import crop, ps, PNG_W, PNG_H      # noqa: E402

# 補遺図の繰り上げ。S1（欠測3層構造の模式図）は投稿対象から外す。
FIGMAP = {"2": "1", "3": "2", "4": "3", "5": "4"}
DROP = ("SupplFigureS1.png", "SupplFigureS1.pptx")
SKIP_PREFIX = ("NDB抗アレルギー解析_v13", "論文下書き_", "~$", "_v13_base")
# キャプションが変わるので書き出し直す本文図
REEXPORT = (2, 4, 6)


def newname(f):
    m = re.match(r"SupplFigureS([2-5])(.*)$", f)
    if m:
        return "SupplFigureS%s%s" % (FIGMAP[m.group(1)], m.group(2))
    return f.replace("_v13_", "_v14_")


def renumber_text(s):
    """本文中の `Supplementary Figure S2` / `Suppl Fig S2` 等を繰り上げる。

    `Supplementary Table S…` には触らない（`Fig` を含む語にのみ一致させる）。
    """
    return re.sub(r"(Suppl(?:ementary)?\.? Fig(?:ure)? )S([2-5])",
                  lambda m: m.group(1) + "S" + FIGMAP[m.group(2)], s)


def patch_zip(path, repl):
    """zip 内の *.xml を文字列置換する。repl は (old, new, 想定件数) の並び。"""
    zin = zipfile.ZipFile(path)
    parts, counts = {}, {old: 0 for old, _, _ in repl}
    for item in zin.infolist():
        data = zin.read(item.filename)
        if item.filename.endswith(".xml"):
            x = data.decode("utf-8")
            for old, new, _ in repl:
                counts[old] += x.count(old)
                x = x.replace(old, new)
            data = x.encode("utf-8")
        parts[item.filename] = data
    infos = list(zin.infolist())
    zin.close()
    for old, _, want in repl:
        if counts[old] != want:
            raise SystemExit("%s: %r が %d 件（想定 %d 件）"
                             % (os.path.basename(path), old, counts[old], want))
    tmp = path + ".tmp"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in infos:
            zout.writestr(item, parts[item.filename])
    shutil.move(tmp, path)


# --- まとめ xlsx：シート名（workbook.xml と グラフの参照式）とタイトル文字列 -------
SHEETS = [("S2A", "S1A"), ("S2B", "S1B"), ("S3", "S2"),
          ("S4A", "S3A"), ("S4B", "S3B"), ("S5", "S4")]
# 参照式の出現回数（'S5' が 54 など。patch_zip の想定件数に使う）
REF_COUNT = {"S2A": 24, "S2B": 6, "S3": 12, "S4A": 12, "S4B": 8, "S5": 54}

SUPPLFIG_XLSX = (
    [('name="%s"' % a, 'name="%s"' % b, 1) for a, b in SHEETS] +
    [("'%s'!" % a, "'%s'!" % b, REF_COUNT[a]) for a, b in SHEETS] +
    [("Suppl Fig S2A.", "Suppl Fig S1A.", 1),
     ("Suppl Fig S2B.", "Suppl Fig S1B.", 1),
     ("Suppl Fig S3.", "Suppl Fig S2.", 1),
     ("Suppl Fig S4A.", "Suppl Fig S3A.", 1),
     ("Suppl Fig S4B.", "Suppl Fig S3B.", 1),
     ("Supplementary Figures S2-S5 (submission bundle, manuscript v13)",
      "Supplementary Figures S1-S4 (submission bundle, manuscript v14)", 1),
     ("S2A  Generic share", "S1A  Generic share", 1),
     ("S2B  Epinastine", "S1B  Epinastine", 1),
     ("S3   Male/female", "S2   Male/female", 1),
     ("S4A  National", "S3A  National", 1),
     ("S4B  Three agents", "S3B  Three agents", 1),
     ("S5   Suppression", "S4   Suppression", 1),
     ("(ratio = 1 in S3, the FY2021/FY2022 specification change in S2 and S4)",
      "(ratio = 1 in S2, the FY2021/FY2022 specification change in S1 and S3)", 1),
     ("Generated by build_supplfig_en_v12.py.",
      "Generated by build_supplfig_en_v12.py; figure numbers shifted up by "
      "build_v14_folder.py (former S2-S5).", 1)])

SUPPLFIG_PPTX = [
    ("Supplementary Figure S2. Generic", "Supplementary Figure S1. Generic", 1),
    ("Supplementary Figure S3. Male", "Supplementary Figure S2. Male", 1),
    ("Supplementary Figure S4. National", "Supplementary Figure S3. National", 1),
    ("Supplementary Figure S5. Suppression",
     "Supplementary Figure S4. Suppression", 1),
    ("columns of sheet S2A", "columns of sheet S1A", 1),
]

FIGURE_PPTX = {
    "Figure2.pptx": [("Supplementary Figure S3", "Supplementary Figure S2", 1)],
    "Figure6.pptx": [("Supplementary Figure S2", "Supplementary Figure S1", 1)],
}


def bump(s):
    """ファイル名と本文中の補遺図番号をまとめて繰り上げる。"""
    s = re.sub(r"SupplFigureS([2-5])",
               lambda m: "SupplFigureS" + FIGMAP[m.group(1)], s)
    return renumber_text(s)


def build_readme():
    src = io.open(os.path.join(V13, "README.md"), encoding="utf-8").read()
    src = src.replace("投稿用ファイル 対応表（原稿 v13・投稿改定ver）",
                      "投稿用ファイル 対応表（原稿 v14・投稿改定ver）")
    src = src.replace("_v13_提出", "_v14_提出")
    src = src.replace("**Suppl Fig S1〜S5**", "**Suppl Fig S1〜S4**")
    src = src.replace(
        "- 英訳時は図中に日本語が残っていないか確認する"
        "（Suppl Fig S1〜S5 は日本語が残っている）。",
        "- 補遺図は英語版（`SupplFigureS1_en.png`〜`S4_en.png` と "
        "`SupplFigureSまとめ_v14_提出`）を投稿に用いる。日本語版の "
        "`SupplFigureS1.png`〜`S4.png` は同じ値の原図として残してある。")
    out = []
    for line in src.split("\n"):
        if line.startswith("| `SupplFigureS1.png`") or \
           line.startswith("| `SupplFigureS1.pptx`"):
            continue                                    # 模式図の行を落とす
        if line.startswith("|"):
            # 表の最終列（コピー元のパス、および v10〜v12 の変更履歴）は
            # 当時のファイル名・図番号を指すので触らない
            cells = line.split("|")
            body = "|".join(bump(c) for c in cells[:-2])
            line = "|".join([body] + cells[-2:])
        else:
            line = bump(line)
        out.append(line)
    return "\n".join(out) + V14_SECTION


V14_SECTION = """

---

## v14 での変更（v13 からの差分）

数値の再計算はない。投稿前の最終チェックで見つかった外形上の問題を処理した。
内容は原稿 md の付記16 を参照。

| 変更 | 対象 |
|---|---|
| **Suppl Fig S1（欠測3層構造の模式図）を投稿対象から外し、S2〜S5 を S1〜S4 に繰り上げ** | 原稿 docx・md、補遺図のファイル名・CSVの説明行、まとめ pptx/xlsx、`Figure2.pptx`・`Figure6.pptx` の note |
| **本文から引用のなかった補遺に引用を追加** | Suppl Table S1（Methods）、Suppl Table S6・Suppl Fig S3（Results） |
| **抄録を圧縮**（1,293字・英訳約435語 → 913字・英訳299語） | 原稿 docx・md。250語制限の投稿先向けの削除候補は作業原稿の抄録に ※ で示した |
| **`Figure4.png` を pptx から書き出し直し** | v13 は pptx のキャプションだけ訂正され PNG に「1.9x」「37.7 pp」が残っていた。`Figure2.png`・`Figure6.png` も繰り上げに合わせて再書き出し |

S1 を落とした理由は、(1) 本文から一度も引用されていない、(2) 図中が全面日本語で
英語版がない、(3) 図中の数値が v9 以前のまま（52品目・62行・245,754 mL・0.105%、
第9〜10回は上位500のみ、レボカバスチン+427%、クロモグリク酸Na +16,000%）で本文と
矛盾する、の3点である。`SupplFigure_en_README.md`（2026-09-06）の
「投稿には含めない」という方針にも合致する。

| 旧 | 新 | 内容 |
|---|---|---|
| Suppl Fig S1 | （削除） | 欠測3層構造の模式図 |
| Suppl Fig S2 | **S1** | 後発品比率と製剤構成の推移 |
| Suppl Fig S3 | **S2** | 主要3成分合計の男/女比 |
| Suppl Fig S4 | **S3** | 全国処方量（mL）の推移と識別区間 |
| Suppl Fig S5 | **S4** | 品目非掲載まで拡張した感度分析 |

まとめ xlsx のシート名も `S1A`/`S1B`/`S2`/`S3A`/`S3B`/`S4` に改めた。シート名は
グラフの参照式にも現れるため、openpyxl で開き直さず zip の XML を直接書き換えている
（ネイティブグラフを保つため）。生成元の `build_supplfig_en_v12.py` は旧番号のままで、
繰り上げは `build_v14_folder.py` が行う。

**投稿には `NDB抗アレルギー解析_v14_clean.docx` を使うこと。**

再生成: `python apply_docx_v14.py` → `python apply_md_v14.py` →
`python build_v14_folder.py` → `python verify_v14.py`
"""

EN_README = """# Supplementary Figures（英語版・公開用）対応表

生成: `python ../build_supplfig_en_v12.py`（`投稿改定ver/` で実行）ののち、
`build_v14_folder.py` が図番号を1つずつ繰り上げる。生成元スクリプトは旧番号
（S2〜S5）のままである。

## Suppl Fig S1（旧）の扱い（2026-09-07・v14）

旧 `SupplFigureS1.png` / `.pptx`（欠測3層構造と識別区間の導出の模式図）は
**教室内向けの解説資料であり、投稿には含めない**。v13 までは原稿に legend だけが
残っていたが、v14 で legend を削除し、以降の図番号を繰り上げた（原稿 付記16-1）。
ファイルは `投稿用v13/` に残してあり、`投稿用v14/` には複製していない。

| 旧 | 新 |
|---|---|
| Suppl Fig S1 | （削除） |
| Suppl Fig S2 | **S1** |
| Suppl Fig S3 | **S2** |
| Suppl Fig S4 | **S3** |
| Suppl Fig S5 | **S4** |

## ファイル

| ファイル | 内容 |
|---|---|
| `SupplFigureS1_en.png` 〜 `S4_en.png` | 英語版の図（300 dpi）。日本語版と同じ描画規則・同じ値 |
| `SupplFigureS1_data_en.csv` 〜 `S4_data_en.csv` | 図に描いた値そのもの。先頭に `#` の説明行（読込時は `comment='#'`） |
| `SupplFigureSまとめ_v14_提出.xlsx` | 1パネル1シート（S1A / S1B / S2 / S3A / S3B / S4）。データ表＋Excelネイティブグラフ＋`Notes` シート |
| `SupplFigureSまとめ_v14_提出.pptx` | 1 Figure = 1スライド（4枚）。グラフはネイティブ。上部に英文タイトル、下部に legend 相当の note |

## データの出どころ

| パネル（新番号） | 元データ |
|---|---|
| S1A | `SupplTableS9.csv`（後発品シェアの合算識別区間・9成分のうち6成分） |
| S1B | `論文図表/csv/Fig5_ge_formulation_bounds__Fig5A_epinastine_LX.csv` |
| S2 | `論文図表/csv/Tables_123_bounds__Table2_MF_ratio.csv`（Table 2 の男/女比） |
| S3 | `SupplFigureS3_data.csv`（旧 `SupplFigureS4_data.csv`。列名を英語に整えて再出力） |
| S4 | `unlisted_sensitivity.csv` |

まとめ xlsx の全セルが上記の元データと一致することは
`build_supplfig_en_v12.py` の実行後に照合済み（不一致 0）。

## Excel グラフでの表現（PNG との違い）

Excel のネイティブグラフで再現できない要素は、意味を落とさないように置き換えてある。

- **S1A・S3A・S3B**: PNG の網掛け／ひげを **カスタム誤差範囲**（プラス側＝上限−下限）で表現。
  S3 は下限の折れ線＋上向きのひげなので、PNG の網掛けと同じ範囲を示す。
- **S2**: 横棒グラフだと軸の最小値から棒が伸び、白い棒で下側を隠す必要があって
  幅の狭い区間が枠線に潰れる。このため **対数軸の散布図＋X方向の誤差範囲**にした。
  マーカーは区間の幾何中点で、**点推定ではない**。Excel の散布図は文字カテゴリを
  取れないので、y 軸は列 B の年齢階級の番号（21 = 0-4 … 1 = 100+）。
- **S4**: 9成分＝9個のグラフを1シートに並べ、すべて対数軸。軸範囲は10のべき乗に丸めてある。
- 値軸に引けない基準線（S2 の比=1、S1・S3 の2021→2022年度の公開仕様変更の縦破線）は
  各シートの note に明記した。PNG と PPTX には描いてある。
"""


def main():
    os.makedirs(V14, exist_ok=True)
    n = 0
    for f in sorted(os.listdir(V13)):
        if f.startswith(SKIP_PREFIX) or f in DROP:
            continue
        src = os.path.join(V13, f)
        if not os.path.isfile(src) or f in ("README.md", "SupplFigure_en_README.md"):
            continue
        shutil.copy2(src, os.path.join(V14, newname(f)))
        n += 1
    print("%d files copied -> %s" % (n, V14))

    # 補遺図の CSV の説明行
    k = 0
    for f in sorted(os.listdir(V14)):
        if not (f.startswith("SupplFigureS") and f.endswith(".csv")):
            continue
        p = os.path.join(V14, f)
        s = io.open(p, encoding="utf-8").read()
        s2 = renumber_text(s)
        if s2 != s:
            io.open(p, "w", encoding="utf-8", newline="").write(s2)
            k += 1
    print("補遺図CSVの説明行を書き換え: %d ファイル" % k)

    # まとめファイルと本文図 pptx
    patch_zip(os.path.join(V14, "SupplFigureSまとめ_v14_提出.xlsx"), SUPPLFIG_XLSX)
    patch_zip(os.path.join(V14, "SupplFigureSまとめ_v14_提出.pptx"), SUPPLFIG_PPTX)
    for f, repl in FIGURE_PPTX.items():
        patch_zip(os.path.join(V14, f), repl)
    print("まとめファイル・Figure2/6 の pptx を書き換え")

    # 本文図の PNG を書き出し直す
    print("PNG を書き出し中（PowerPoint COM）...")
    names = "', '".join("Figure%d" % i for i in REEXPORT)
    ps("""
$ErrorActionPreference = 'Stop'
$dest = '%s'
$ppt = New-Object -ComObject PowerPoint.Application
foreach ($n in @('%s')) {
  $pres = $ppt.Presentations.Open((Join-Path $dest ($n + '.pptx')), $false, $false, $false)
  $pres.Slides.Item(1).Export((Join-Path $dest ($n + '.png')), 'PNG', %d, %d)
  $pres.Close()
}
$ppt.Quit()
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($ppt) | Out-Null
""" % (V14, names, PNG_W, PNG_H))
    for i in REEXPORT:
        crop(os.path.join(V14, "Figure%d.png" % i))
    print("  Figure%s.png を書き出し直した" % "・".join(str(i) for i in REEXPORT))

    io.open(os.path.join(V14, "README.md"), "w",
            encoding="utf-8", newline="\n").write(build_readme())
    io.open(os.path.join(V14, "SupplFigure_en_README.md"), "w",
            encoding="utf-8", newline="\n").write(EN_README)
    print("README written")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    main()
